### ISSUE TITLE
error on world boss

### ISSUE THREAD

**Issue by Tactlesshail** [9-9-9-9/Bit-Heroes-bot#100]
bh.bot.common.exceptions.InvalidDataException: Unable to detect index of selected radio button among 1 results
        at bh.bot.app.AbstractApplication.detectRadioButtons(AbstractApplication.java:698)
        at bh.bot.app.AbstractApplication.tryEnterWorldBoss(AbstractApplication.java:1326)
        at bh.bot.app.AfkApp.doLoop(AfkApp.java:353)
        at bh.bot.app.AfkApp.lambda$internalRun$0(AfkApp.java:117)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
** ERR ** doLoop encountered error!

i get this error when it tries to do world boss. It just started doing this today i believe

**Comment by 9-9-9-9** [comment]
@daredoes Could you please check? Since I already left game for a long time.

Problem may caused by the shape of the radio buttons at World Boss selection has changed

**Comment by daredoes** [comment]
I'll check into this. Hopefully should be easy to fix. I've had my bot turned off for a week, so I didn't notice

**Comment by daredoes** [comment]
@Tactlesshail this might be related to your own personal setup. No issue on my end testing for a few days

**Comment by Tactlesshail** [comment]
I don't know could be. I even reinstalled latest version and still happens.
I've not changed anything on game window
